name: Feature Request
title: '[FR] title'
description: Open a Feature Request.
labels: ['enhancement']
assignees: ['daviddodo']
projects: ['daviddodo/2']
body:
  - type: textarea
    attributes:
      label: Add a description222222
      description: Add your description here...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context222222222
      description: Add context/requirements here...
    validations:
      required: false